config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  match 'features', to: 'features#index', via: :get
  match 'browsers', to: 'browsers#index', via: :get
  match 'graphs', to: 'graphs#index', via: :get

  # Add browser pages with a URL that uses the browser_id,
  # e.g. `/browsers/chrome`.
  resources :browsers, param: :browser_id, only: [:show]

  resources :features, param: :slug, only: [:show]

  root 'welcome#index'
end

app/views/shared/_footer.html.erb
<footer class="site-footer">
  <ul>
    <li>
      Built with data from <%= link_to "v#{Rails.configuration.mdn_bcd_version}", "https://github.com/mdn/browser-compat-data/releases/tag/v#{Rails.configuration.mdn_bcd_version}" %> of the <%= link_to "MDN Browser Compatibility Data", "https://github.com/mdn/browser-compat-data" %> project.
    </li>
    <li>
      <%= link_to "View source", "https://github.com/connorshea/mdn-compat-data-explorer" %>
    </li>
    <li>
      <%= link_to "Report an issue", "https://github.com/connorshea/mdn-compat-data-explorer/issues" %>
    </li>
  </ul>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light <%= "sticky-header" if @sticky_header == true %>">
  <%= link_to "BCD Explorer", root_path, class: "d-inline-block d-md-none navbar-brand" %>
  <%= link_to "MDN Browser Compatibility Data Explorer", root_path, class: "d-none d-md-inline-block navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= active_link_to "Browsers", browsers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= active_link_to "Features", features_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= active_link_to "Graphs", graphs_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>