config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  match 'features', to: 'features#index', via: :get
  match 'browsers', to: 'browsers#index', via: :get
  match 'graphs', to: 'graphs#index', via: :get

  # Add browser pages with a URL that uses the browser_id,
  # e.g. `/browsers/chrome`.
  resources :browsers, param: :browser_id, only: [:show]

  resources :features, param: :slug, only: [:show]

  root 'welcome#index'
end

app/models/browser.rb
# == Schema Information
#
# Table name: browsers
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  releases   :jsonb
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  browser_id :string
#

class Browser < ApplicationRecord
  store_accessor :releases, :release_date, :release_notes, :status

  validates :browser_id, presence: true
  validates :name, presence: true, uniqueness: true
  validates :releases, uniqueness: true
end

app/controllers/browsers_controller.rb
class BrowsersController < ApplicationController
  def index
    @browsers = helpers.browser_releases_sorter(Browser.all)

    respond_to do |format|
      format.html
    end
  end

  def show
    @browser = Browser.find_by(browser_id: params[:browser_id])
    @browser = helpers.browser_releases_sorter(@browser)
  end
end

app/helpers/browsers_helper.rb
module BrowsersHelper
  def browser_releases_sorter(browsers)
    # Handle two main cases for the browsers value:
    # - where only a single Browser object is passed
    # - when an ActiveRecord Relation with multiple browsers is passed
    if browsers.kind_of?(Browser)
      release_sorter(browsers)
    else
      browsers.each do |browser|
        release_sorter(browser)
      end
    end

    return browsers
  end

  private

  def release_sorter(browser)
    # https://stackoverflow.com/questions/808318/sorting-a-ruby-array-of-objects-by-an-attribute-that-could-be-nil
    # Sorts the array and leaves nil values at the end.
    browser.releases = browser.releases.sort { |a, b| a["release_date"] && b["release_date"] ? a["release_date"] <=> b["release_date"] : a["release_date"] ? -1 : 1 }

    nil_values = []
    browser_releases_with_release_dates = []
    browser.releases.each_with_index do |release_info, i|
      # Collect all release dates which are nil so we can sort them
      # separately.
      if release_info["release_date"].nil?
        nil_values << browser.releases[i]
      # Collect all releases with release date values.
      else
        browser_releases_with_release_dates << browser.releases[i]
      end
    end

    # Replace browser.releases with the array of releases that have valid
    # release dates. This is a workaround means of deleting all nil values.
    browser.releases = browser_releases_with_release_dates

    # Sort the nil_values array by the version number, then append it to the
    # browser releases.
    VersionSorter.sort!(nil_values) { |release| release["version"] }
    nil_values.each { |release| browser.releases.push(release) }
  end
end

app/views/browsers/index.html.erb
<% content_for :title, "Browsers" %>

<div class="container">
  <div class="row py-4">
    <div class="col-12">
      <h1>Browsers</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-12 sticky-column">
      <div class="card mb-4">
        <div class="card-header bg-light">
          Jump to...
        </div>
        <ul class="list-group list-group-flush">
          <% @browsers.each do |browser| %>
            <li class="list-group-item"><%= link_to browser.name, "##{browser.name.downcase.gsub(' ', '_')}" %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="col-lg-8 col-12">
      <% @browsers.each do |browser| %>
        <div class="card card-no-overflow mb-4">
          <table id="<%= "#{browser.name.downcase.gsub(' ', '_')}" %>" class="table mb-0 browser-table width-full">
            <thead>
              <tr class="text-center bg-light border-transparent rounded-top">
                <th class="border-top-0" colspan="4"><%= link_to browser.name, browser_path(browser.browser_id) %></th>
              </tr>
              <tr>
                <th>Version</th>
                <th>Status</th>
                <th>Release date</th>
                <th>Release notes</th>
              </tr>
            </thead>
            <tbody>
              <% browser.releases.each do |release| %>
                <tr>
                  <td><%= release['version'] %></td>
                  <td><%= release['status'] %></td>
                  <td>
                    <% unless release['release_date'].blank? %>
                      <%# Format dates like April 2, 2017, this is the same as long but without the leading 0 for days.%>
                      <%= Date.parse(release['release_date']).strftime("%B %-d, %Y") %>
                    <% end %>
                  </td>
                  <td class="release-notes">
                    <% unless release['release_notes'].blank? %>
                      <%= link_to "📰", release['release_notes'], title: "Release notes" %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/browsers/show.html.erb
<% content_for :title, @browser.name %>

<div class="container">
  <div class="row py-4">
    <div class="col-12">
      <h1><%= @browser.name %></h1>
    </div>
  </div>
  <div class="row">

    <div class="col-12">
      <div class="card card-no-overflow mb-4">
        <table id="<%= "#{@browser.name.downcase.gsub(' ', '_')}" %>" class="table mb-0 browser-table width-full">
          <thead>
            <tr class="text-center bg-light border-transparent rounded-top">
              <th class="border-top-0" colspan="5"><%= @browser.name %></th>
            </tr>
            <tr>
              <th>Version</th>
              <th>Status</th>
              <th>Release date</th>
              <th>Release notes</th>
              <th class="features-column">Features</th>
            </tr>
          </thead>
          <tbody>
            <% @browser.releases.each_with_index do |release, i| %>
              <tr>
                <td><%= release['version'] %></td>
                <td><%= release['status'] %></td>
                <td>
                  <% unless release['release_date'].blank? %>
                    <%# Format dates like April 2, 2017, this is the same as long but without the leading 0 for days.%>
                    <%= Date.parse(release['release_date']).strftime("%B %-d, %Y") %>
                  <% end %>
                </td>
                <td class="release-notes">
                  <% unless release['release_notes'].blank? %>
                    <%= link_to "📰", release['release_notes'], title: "Release notes" %>
                  <% end %>
                </td>
                <td class="features-column">
                  <p>Features added (<%= browser_release_features(@browser.browser_id, release['version']).count(:name) %>):</p>

                  <a class="btn btn-primary" data-toggle="collapse" href='<%= "#collapseReleaseFeatures#{i}" %>' role="button" aria-expanded="false" aria-controls='<%= "collapseReleaseFeatures#{i}" %>'>
                    Toggle features
                  </a>

                  <div class="collapse" id='<%= "collapseReleaseFeatures#{i}" %>'>
                    <% browser_release_features(@browser.browser_id, release['version']).each do |feature| %>
                      <p><%= link_to feature.name, feature_path(feature.slug) %></p>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>